### PR TITLE
Remove old svgs and keep the original .tex.md files

### PR DESCRIPTION
**Pull request by he7d3r**
Also remove unnecessary "Hello, world"

### CODE REVIEW

**Review by montali — APPROVED** [review]
This is great mate! Thanks a lot for your help.

**Comment by he7d3r** [comment]
I see this was reverted in 42dc547cdea9f4576fad63b4a0e9918c9d48982c. Do you have details on what was wrong?

**Comment by montali** [comment]
Hi Helder! Sorry about this, but I tried using it and it just deleted the svgs without creating new ones, and missed the context :(
Therefore, I reverted everything. If you manage to fix those problems I’d be more than happy to re-merge!
Thanks a lot for your help.

**Comment by he7d3r** [comment]
Hi again! I forked your repo and was able to [use it like this](https://github.com/he7d3r/readme2tex-action-test/commit/3beee9c8ca14f0b57e13bbc2938959369249c8fd) (similar to what [you tried to do here](https://github.com/montali/unibo-ai/commit/e0b7620b6f5ad11967b2f29712051271fc900d01)) to build the README of [this simple test](https://github.com/he7d3r/readme2tex-action-test/commits/master) after [making these changes](https://github.com/he7d3r/readme2tex-action/commit/e20bc1cf7639c9b1934cb648f9d96437743a1f46?w=1). I'll try to deal with the the deletion of SVGs some other day...

**Comment by montali** [comment]
> Hi again! I forked your repo and was able to [use it like this](https://github.com/he7d3r/readme2tex-action-test/commit/3beee9c8ca14f0b57e13bbc2938959369249c8fd) (similar to what [you tried to do here](https://github.com/montali/unibo-ai/commit/e0b7620b6f5ad11967b2f29712051271fc900d01)) to build the README of [this simple test](https://github.com/he7d3r/readme2tex-action-test/commits/master) after [making these changes](he7d3r/readme2tex-action). I'll try to deal with the the deletion of SVGs some other day...

Hi Helder! I'm trying to open your links but they return a 404 😔

**Comment by he7d3r** [comment]
Oh. Sorry for that. I fixed the links now.

**Comment by montali** [comment]
@he7d3r It now works perfectly! Thanks a lot for the effort you put into this. Could you open another PR?

**Comment by he7d3r** [comment]
Done at https://github.com/montali/readme2tex-action/pull/2

**Pull request merged**
